0.0.6

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -1,23 +1,58 @@
-name: Deploy Docker Image
+name: Build, Push and Deploy Docker Image
 
 on:
-  workflow_run:
-    workflows: ['Build and Push Docker Image']
-    types:
-      - completed
+  push:
+    tags:
+      - 'v*.*.*'
+
+permissions:
+  contents: read
+  packages: write
 
 jobs:
+  build-and-push:
+    runs-on: ubuntu-latest
+
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v4
+
+      - name: Set up Docker Buildx
+        uses: docker/setup-buildx-action@v3
+
+      - name: Log in to GitHub Container Registry
+        uses: docker/login-action@v3
+        with:
+          registry: ghcr.io
+          username: ${{ github.actor }}
+          password: ${{ secrets.GITHUB_TOKEN }}
+
+      - name: Extract tag name
+        run: echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
+
+      - name: Build and push Docker image
+        uses: docker/build-push-action@v6
+        with:
+          context: .
+          push: true
+          build-args: NODE_OPTIONS="--max-old-space-size=4096"
+          tags: |
+            ghcr.io/${{ github.repository_owner }}/quoi-regarder_website:${{ env.TAG_NAME }}
+            ghcr.io/${{ github.repository_owner }}/quoi-regarder_website:latest
+
   deploy:
     runs-on: ubuntu-latest
+    needs: build-and-push
+
     steps:
       - name: Connect to server and deploy
-        uses: appleboy/ssh-action@v0.1.7
+        uses: appleboy/ssh-action@v1.2.0
         with:
           host: ${{ secrets.SERVER_HOST }}
           username: ${{ secrets.SERVER_USER }}
           key: ${{ secrets.SERVER_SSH_KEY }}
           script: |
-            set -e  # Exit the script if any command fails
+            set -e  # Stop the script if any command fails
 
             echo "🔄 Connecting to the server..."
             docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}
